# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"dimensions": "00_core.ipynb",
         "Dim": "00_core.ipynb",
         "positive": "00_core.ipynb",
         "manhattan": "00_core.ipynb",
         "binarysearch": "00_core.ipynb",
         "bfs": "00_core.ipynb"}

modules = ["aoc.py"]

doc_url = "https://jvanelteren.github.io/aocutils/"

git_url = "https://github.com/jvanelteren/aocutils/tree/branch/"

def custom_doc_links(name): return None
